#!/bin/tcsh

alias MATH 'set \!:1 = `echo "\!:3-$" | bc -l`'
set div = 100.0

set i = 1
while ($i <= 30)
MATH res = $i / $div 
echo $i
echo $res

set j = 1
while ($j <= 100)
echo $j


touch parametres.par
echo "pointage: [0.0,0.0]'"				>>parametres.par
echo "source: [0.0,0.0]'      (1.0)%        {1.1}"	>>parametres.par
echo "nombre de photons: [1000000]" 			>>parametres.par
echo "bande en energie:  [0.5,100]kev"			>>parametres.par
echo "energie fixe: [$j]kev"				>>parametres.par
echo "graine: [1]"					>>parametres.par
echo "nombres de miroirs: [1]"				>>parametres.par
echo "rayon du miroir si un seul miroir: [$res]"	>>parametres.par
echo "focale: [30]m"					>>parametres.par
echo "position du module miroir: [0.0,0.0,-0.2]m"	>>parametres.par
echo "erreur d'alignement des miroirs: [15.0]"		>>parametres.par
echo "erreur de positionnement des miroirs: [0.00015,0.00015,0.0005]m"		>>parametres.par
echo "erreur de forme des miroirs: [3.85]"					>>parametres.par
echo "polissage des miroirs: [0.25]"						>>parametres.par
echo "position de la cible 1: [0.0,-0.574,-0.3]m"				>>parametres.par
echo "position de la cible 2: [0.497,-0.287,-0.3]m"				>>parametres.par
echo "position de la cible 3: [-0.497,-0.287,-0.3]m"				>>parametres.par
echo "biais de la mesure du STR du MSC: [3.2,3.3,5.0]"				>>parametres.par
echo "bruit pixel de la mesure du STR du MSC: [2.0]"				>>parametres.par
echo "hauteur du collimateur: [0.1]m"						>>parametres.par
echo "rayon du collimateur: [10]m"						>>parametres.par
echo "position du LED: [0.0,0.0,0.196]m"					>>parametres.par
echo "position du HED: [0.0,0.0,0.186]m"					>>parametres.par
echo "position du CLM du DSC: [0.5,0.0,0.196]m"					>>parametres.par
echo "biais de la mesure du STR du DSC: [3.2,3.3,5.0]"				>>parametres.par
echo "bruit pixel de la mesure du STR du DSC: [2.0]"				>>parametres.par
echo "biais de la mesure du CLM du DSC: [0.2,0.2,0.2]"				>>parametres.par
echo "bruit pixel de la mesure du CLM du DSC: [0.4]"				>>parametres.par
echo "dimensions du LED: [0.08,0.08]m"						>>parametres.par
echo "dimensions du HED: [0.084375,0.084375]m"					>>parametres.par
echo "nombre de pixels du LED: [128,128]"					>>parametres.par
echo "nombre de pixels du HED: [135,135]"					>>parametres.par
echo "taille des pixels du LED: [0.000625]m"					>>parametres.par
echo "taille des pixels du HED: [0.000625]m"					>>parametres.par
echo "nombre d'etats de la formation: [10000]"					>>parametres.par
echo "defocalisation: [0.0]m"							>>parametres.par
echo "fichier parametre face d'entree des miroirs: [./input/mirrors_entree.par]"	>>parametres.par
echo "fichier parametre des miroirs paraboliques: [./input/mirrors_para.par]"		>>parametres.par
echo "fichier parametre des miroirs hyperboliques: [./input/mirrors_hyper.par]"		>>parametres.par
echo "fichier parametre des coefficients de reflexion: [./input/coeff_reflection_large.par]"	>>parametres.par
echo "fichier donnees des mouvements du MSC: [./input/mouvement_MSC.data]"		>>parametres.par
echo "fichier donnees des mouvements du DSC: [./input/mouvement_DSC_astrium.data]"	>>parametres.par
echo "fichier parametre PSF: [./output/PSF.data]"					>>parametres.par	
echo "fichier donnees PSF reelle: [./output/PSF_reelle.data]"				>>parametres.par
echo "fichier donnees PSF corrigee: [./output/PSF_corrige.data]"		>>parametres.par
echo "fichier donnees spectre LED total: [./output/spec_LED_total.data]"				>>parametres.par
echo "fichier donnees spectre HED total: [./output/spec_HED_total.data]"				>>parametres.par
echo "fichier donnees image et spectre LED: [./output/spec_LED_pixels.data]"				>>parametres.par
echo "fichier donnees image et spectre HED: [./output/spec_HED_pixels.data]"				>>parametres.par
echo "fichier donnees image corrigee et spectre LED: [./output/spec_LED_pixels_corr.data]"				>>parametres.par
echo "fichier donnees image corrigee et spectre HED: [./output/spec_HED_pixels_corr.data]"				>>parametres.par

modeles/miroir_unique
DynamiX

set line = `cat "/users/chauvin/These/DynamiX/output/PSF.data"`
touch effarea_1miroir_m.txt
echo $j "$line" >>effarea_1miroir_m.txt

rm parametres.par

@ j = $j + 1
end

@ i = $i + 1
end


#more angle70.max
