#!/bin/tcsh

alias MATH 'set \!:1 = `echo "\!:3-$" | bc -l`'

set i = 0
while ($i <= 100)
echo $i


set j = 0
while ($j <= 60)
echo $j
set div = 10.0
MATH res = $j / $div 
echo $res

touch parametres.par
echo "pointage: [0.0,0.0]'"				>>parametres.par
echo "source: [0.0,0.0]'      (1.0)%        {1.1}"	>>parametres.par
echo "nombre de photons: [1000000]" 			>>parametres.par
echo "bande en energie:  [$res,100]kev"			>>parametres.par
echo "energie fixe: [1]kev"				>>parametres.par
echo "graine: [$i]"					>>parametres.par
echo "nombres de miroirs: [100]"			>>parametres.par
echo "focale: [20.0]m"					>>parametres.par
#echo "position du module miroir: [0.0,0.0,-0.2]m"	>>parametres.par
echo "position du module miroir: [0.0,0.0,0.0]m"	>>parametres.par
echo "erreur d'alignement des coquilles: [15.0]"	>>parametres.par
echo "erreur de positionnement des coquilles: [0.00015,0.00015,0.0005]m"	>>parametres.par
echo "polissage des miroirs: [3.85]"						>>parametres.par
echo "position de la cible 1: [0.0,-0.574,-0.3]m"				>>parametres.par
echo "position de la cible 2: [0.497,-0.287,-0.3]m"				>>parametres.par
echo "position de la cible 3: [-0.497,-0.287,-0.3]m"				>>parametres.par
echo "biais de la mesure du STR du MSC: [3.2,3.3,5.0]"				>>parametres.par
echo "bruit pixel de la mesure du STR du MSC: [2.0]"				>>parametres.par
echo "hauteur du collimateur: [0.1]m"						>>parametres.par
echo "rayon du collimateur: [10]m"						>>parametres.par
echo "position du LED: [0.0,0.0,0.196]m"					>>parametres.par
echo "position du HED: [0.0,0.0,0.186]m"					>>parametres.par
echo "position du CLM du DSC: [0.5,0.0,0.196]m"					>>parametres.par
echo "biais de la mesure du STR du DSC: [3.2,3.3,5.0]"				>>parametres.par
echo "bruit pixel de la mesure du STR du DSC: [2.0]"				>>parametres.par
echo "biais de la mesure du CLM du DSC: [0.2,0.2,0.2]"				>>parametres.par
echo "bruit pixel de la mesure du CLM du DSC: [0.4]"				>>parametres.par
echo "dimensions du LED: [0.08,0.08]m"						>>parametres.par
echo "dimensions du HED: [0.084375,0.084375]m"					>>parametres.par
echo "nombre de pixels du LED: [128,128]"					>>parametres.par
echo "nombre de pixels du HED: [135,135]"					>>parametres.par
echo "taille des pixels du LED: [0.000625]m"					>>parametres.par
echo "taille des pixels du HED: [0.000625]m"					>>parametres.par
echo "nombre d'etats de la formation: [10000]"					>>parametres.par
echo "defocalisation: [0.0]m"							>>parametres.par
echo "fichier parametre face d'entree des miroirs: [./input/mirrors_entree.par]"	>>parametres.par
echo "fichier parametre des miroirs paraboliques: [./input/mirrors_para.par]"		>>parametres.par
echo "fichier parametre des miroirs hyperboliques: [./input/mirrors_hyper.par]"		>>parametres.par
echo "fichier parametre des coefficients de reflexion: [./input/coeff_reflection.par]"	>>parametres.par
echo "fichier donnees des mouvements du MSC: [./input/mouvement_MSC.data]"		>>parametres.par
echo "fichier donnees des mouvements du DSC: [./input/mouvement_DSC_astrium.data]"	>>parametres.par
echo "fichier parametre PSF: [./output/PSF.data]"					>>parametres.par	
echo "fichier donnees PSF reelle: [./output/PSF_reelle.data]"				>>parametres.par
echo "fichier donnees PSF corrigee: [./output/PSF_corrige.data]"		>>parametres.par
echo "fichier donnees spectre LED total: [./output/spec_LED_total.data]"				>>parametres.par
echo "fichier donnees spectre HED total: [./output/spec_HED_total.data]"				>>parametres.par
echo "fichier donnees image et spectre LED: [./output/spec_LED_pixels.data]"				>>parametres.par
echo "fichier donnees image et spectre HED: [./output/spec_HED_pixels.data]"				>>parametres.par
echo "fichier donnees image corrigee et spectre LED: [./output/spec_LED_pixels_corr.data]"				>>parametres.par
echo "fichier donnees image corrigee et spectre HED: [./output/spec_HED_pixels_corr.data]"				>>parametres.par

DynamiX

set line = `cat "/users/chauvin/These/DynamiX/output/PSF.data"`
touch SX_hew_mirrormotion_new2.txt
echo $res "$line" >>SX_hew_mirrormotion_new2.txt

rm parametres.par

@ j = $j + 1
end

@ i = $i + 1
end

#more angle70.max
